spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/notarize
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 6270
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 80